name: Trigger specs
on:
  workflow_dispatch:
    inputs:
      specs:
        description: Comma-separates spec filenames
        required: true
jobs:
  specs:
    runs-on: ubuntu-20.04
    steps:
      - name: Print specs ğŸ–¨ï¸
        env:
          SPECS: ${{ toJson(github.event.inputs.specs) }}
        run: echo "$SPECS"

      - name: Checkout ğŸ›
        uses: actions/checkout@v3

      - name: Run selected specs ğŸƒ
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:ci
          wait-on: 'http://localhost:8888'
          spec: ${{ github.event.inputs.specs }}
