name: Trigger specs
on:
  workflow_dispatch:
    inputs:
      specs:
        description: Comma-separates spec filenames without spaces
        required: true
      recordingTag:
        description: Cypress Dashboard recording tag
        required: false
        default: Trigger specs

jobs:
  specs:
    runs-on: ubuntu-20.04
    steps:
      - name: Print specs ğŸ–¨ï¸
        env:
          SPECS: ${{ toJson(github.event.inputs.specs) }}
        run: echo "$SPECS"

      - name: Checkout ğŸ›
        uses: actions/checkout@v3

      - name: Run selected specs ğŸƒ
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:ci
          wait-on: 'http://localhost:8888'
          spec: '${{ github.event.inputs.specs }}'
          record: true
          tag: '${{ github.event.inputs.recordingTag }}'
          group: Selected specs
          # each workflow execution should have its own recorded run
          ci-build-id: '${{ github.workflow }} - ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempts }}'
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
